<a id='intro'></a>
## Introduction

### Dataset Description
    This EGX stock database contains companies, daily trading records, and market indices from the Egyptian Exchange within the specified period.

In [2]:
import pandas as pd
import datetime 
import csv

<a id='wrangling'></a>
## Data Wrangling

In [3]:
df = pd.read_csv(r"D:\Projects\Egy stock egyx33\Egxstock-analysis\data\raw.csv")
df2 = pd.read_csv(r"D:\Projects\Egy stock egyx33\Egxstock-analysis\data\stock_data.csv")

In [4]:
df.head(10)

,Date,Company,Symbol,MarketCap,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
0,2025-06-01 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,81.750000,82.239998,81.160004,81.160004,424708,0.0,0.0,0.0
1,2025-06-02 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,81.160004,81.879997,80.010002,80.559998,77620,0.0,0.0,0.0
2,2025-06-03 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,80.559998,80.980003,79.959999,80.110001,136590,0.0,0.0,0.0
3,2025-06-04 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,80.110001,80.650002,79.910004,80.500000,154041,0.0,0.0,0.0
4,2025-06-10 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,80.500000,81.209999,80.019997,80.750000,69382,0.0,0.0,0.0
5,2025-06-11 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,80.750000,81.209999,80.000000,80.209999,92666,0.0,0.0,0.0
6,2025-06-12 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,80.209999,80.599998,78.500000,78.510002,528845,0.0,0.0,0.0
7,2025-06-15 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,78.510002,77.699997,74.500000,76.599998,163295,0.0,0.0,0.0
8,2025-06-16 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,76.599998,78.000000,76.599998,77.070000,181288,0.0,0.0,0.0
9,2025-06-17 00:00:00+03:00,El Sewedy Electric,SWDY.CA,102025871360,77.070000,78.510002,75.500000,75.959999,82074,0.0,0.0,0.0

In [5]:
df2.head()

,Company,Sector,Price,1D,YTD,M.Cap,Date
0,Company,Sector,Price,1D,YTD,M.Cap,Date
1,Abu Dhabi Islamic Bank Egypt,Financials,39.89,-2.47%,+33.41%,47.86,24/03
2,Abu Qir Fertilizers,Basic Materials,94.00,+8.05%,+84.31%,118.61,24/03
3,Acrow Misr,Industrials,127.52,-,+4.64%,7.02,24/03
4,Advanced Pharmaceutical Packaging Co.,Industrials,2.33,-,-,0,24/03

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4640 entries, 0 to 4639
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           4640 non-null   object
 1   Company        4640 non-null   object
 2   Symbol         4640 non-null   object
 3   MarketCap      4640 non-null   int64
 4   Open           4640 non-null   float64
 5   High           4640 non-null   float64
 6   Low            4640 non-null   float64
 7   Close          4640 non-null   float64
 8   Volume         4640 non-null   int64
 9   Dividends      4640 non-null   float64
 10  Stock Splits   4640 non-null   float64
 11  Capital Gains  4640 non-null   float64
dtypes: float64(7), int64(2), object(3)
memory usage: 435.1+ KB

## Cleaning , Fixing Format and Processing The Data :

## Data set 1 :

In [7]:
df.describe()

,MarketCap,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
count,4.640000e+03,4640.000000,4640.000000,4640.000000,4640.000000,4.640000e+03,4640.000000,4640.000000,4640.0
mean,3.742301e+10,28.017820,28.487500,27.719858,28.068615,5.021843e+06,0.001872,0.002922,0.0
std,5.302482e+10,27.041865,27.608807,26.775546,27.153059,1.631203e+07,0.090397,0.068099,0.0
min,9.164430e+08,0.644000,0.649000,0.627000,0.644000,0.000000e+00,0.000000,0.000000,0.0
25%,8.262643e+09,8.180000,8.300000,8.097500,8.187500,3.041320e+05,0.000000,0.000000,0.0
50%,1.932572e+10,19.304999,19.570000,19.135000,19.304999,9.432640e+05,0.000000,0.000000,0.0
75%,4.297567e+10,41.806617,42.607500,41.000000,41.955819,2.833176e+06,0.000000,0.000000,0.0
max,2.683270e+11,161.320007,170.979996,159.009995,170.979996,5.561549e+08,6.000000,3.000000,0.0

In [8]:
df["Capital Gains"].value_counts()

Capital Gains
0.0    4640
Name: count, dtype: int64

In [9]:
df = df.drop(["Capital Gains","Dividends","Stock Splits"],axis=1)

In [11]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

specific_dates = ['2025-06-30', '2025-07-30', '2025-08-30', '2025-09-30',
                  '2025-10-30', '2025-11-30', '2025-12-30', '2025-12-31']
df = df[df['Date'].isin(specific_dates)]

In [14]:
df.isnull().sum()
df.isna().sum()

Date         0
Company      0
Symbol       0
MarketCap    0
Open         0
High         0
Low          0
Close        0
Volume       0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128 entries, 17 to 4595
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       128 non-null    object
 1   Company    128 non-null    object
 2   Symbol     128 non-null    object
 3   MarketCap  128 non-null    int64
 4   Open       128 non-null    float64
 5   High       128 non-null    float64
 6   Low        128 non-null    float64
 7   Close      128 non-null    float64
 8   Volume     128 non-null    int64
dtypes: float64(4), int64(2), object(3)
memory usage: 10.0+ KB

## Data set 2 :

In [16]:
df2.describe()

                         Company      Sector Price   1D  YTD M.Cap   Date
count                        290         306   306  306  301   284    284
unique                       288          33   293  171  217   207     15
top     Misr Chemical Industries  Financials  1.00    -    -     0  24/03
freq                           2          90     6  101   65    39    241

In [17]:
df2 = df2.dropna()
df2.isna().sum()

Company    0
Sector     0
Price      0
1D         0
YTD        0
M.Cap      0
Date       0
dtype: int64

In [18]:
df2['Price'] = pd.to_numeric(df2['Price'], errors='coerce')
df2['M.Cap'] = pd.to_numeric(df2['M.Cap'], errors='coerce')
df2['1D']    = pd.to_numeric(df2['1D'].astype(str).str.replace('%', '', regex=False), errors='coerce')
df2['YTD']   = pd.to_numeric(df2['YTD'].astype(str).str.replace('%', '', regex=False), errors='coerce')

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 283 entries, 0 to 284
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Company  283 non-null    object
 1   Sector   283 non-null    object
 2   Price    281 non-null    float64
 3   1D       182 non-null    float64
 4   YTD      217 non-null    float64
 5   M.Cap    282 non-null    float64
 6   Date     283 non-null    object
dtypes: float64(4), object(3)
memory usage: 17.7+ KB

## EDA (Explore data analysis) :

### formals we will use 

    Range stock prices = (high - low )/ close  
    Daily Return (%) = [(Closing Price − Opening Price) ÷ Opening Price] × 100

    Price vs 52W High = ( Close - High_52W ) / High_52W × 100
    Price vs 52W Low = ( Close - Low_52W ) / Low_52W × 100

    Avg Daily Swing = sum( High - Low ) / n
    
    Portfolio Value = 10,000 × ( Close_t / Close_0 )
    Total Gain = Portfolio Value - 10,000

### 52-Week High/Low Analysis

In [ ]:
df["Range"] = (df["High"]-df["Low"]) /df["Close"]
df["Daily Return"] = ((df['Close'] - df['Open']) / df['Open']) * 100

In [26]:
# Calculate 52-Week High and Low (365 days rolling)
df = df.sort_values(['Company', 'Date']).reset_index(drop=True)

df['High_52W'] = df.groupby('Company')['High'].transform('cummax')
df['Low_52W']  = df.groupby('Company')['Low'].transform('cummin')

# Calculate Price vs 52W High and Low %
df['Price_vs_52W_High'] = ((df['Close'] - df['High_52W']) / df['High_52W']) * 100
df['Price_vs_52W_Low'] = ((df['Close'] - df['Low_52W']) / df['Low_52W']) * 100

### Portfolio Performance & Daily Swing Analysis

In [27]:
# Calculate Portfolio Value (Starting with 10,000 egp)
first_close = df.groupby('Company')['Close'].transform('first')
df['Portfolio_Value'] = 10000 * (df['Close'] / first_close)
df['Total_Gain'] = df['Portfolio_Value'] - 10_000

In [28]:
df

,Date,Company,Symbol,MarketCap,Open,High,Low,Close,Volume,Range,Daily Return,High_52W,Low_52W,Price_vs_52W_High,Price_vs_52W_Low,Portfolio_Value,Total_Gain
0,2025-06-30,Abu Kir Fertilizers,ABUK.CA,73592594432,44.756686,45.236318,44.188235,44.410286,698204,0.023600,-0.773962,45.236318,44.188235,-1.826036,0.502513,10000.000000,0.000000
1,2025-07-30,Abu Kir Fertilizers,ABUK.CA,73592594432,44.587928,45.298492,44.143825,44.419167,703454,0.025995,-0.378491,45.298492,44.143825,-1.941180,0.623738,10001.999675,1.999675
2,2025-09-30,Abu Kir Fertilizers,ABUK.CA,73592594432,46.968317,47.563413,46.897259,47.341362,792468,0.014071,0.794248,47.563413,44.143825,-0.466853,7.243453,10659.999364,659.999364
3,2025-10-30,Abu Kir Fertilizers,ABUK.CA,73592594432,48.500000,48.860001,48.480000,48.599998,496387,0.007819,0.206182,48.860001,44.143825,-0.532137,10.094670,10943.410391,943.410391
4,2025-06-30,Alexandria Container & Cargo Handling,ACGC.CA,1602136192,9.310000,10.380000,9.250000,10.380000,4338221,0.108863,11.493014,10.380000,9.250000,0.000000,12.216217,10000.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-10-30,Telecom Egypt,ETEL.CA,55940739072,50.400002,50.500000,50.000000,50.099998,372094,0.009980,-0.595244,51.980000,37.910000,-3.616778,32.155101,13184.210125,3184.210125
124,2025-06-30,Unit Investments,UNIT.CA,1450209408,7.880000,7.980000,7.800000,7.870000,105493,0.022872,-0.126906,7.980000,7.800000,-1.378448,0.897432,10000.000000,0.000000
125,2025-07-30,Unit Investments,UNIT.CA,1450209408,8.070000,8.400000,8.050000,8.260000,443161,0.042373,2.354406,8.400000,7.800000,-1.666659,5.897436,10495.553175,495.553175
126,2025-09-30,Unit Investments,UNIT.CA,1450209408,10.890000,10.900000,10.700000,10.890000,26502,0.018365,0.000000,10.900000,7.800000,-0.091736,39.615386,13837.357690,3837.357690
127,2025-10-30,Unit Investments,UNIT.CA,1450209408,11.390000,11.490000,11.200000,11.210000,120553,0.025870,-1.580336,11.490000,7.800000,-2.436899,43.717946,14243.964677,4243.964677